version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  development-deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fd:e0:e2:81:80:1b:4d:ee:be:7b:cd:a3:cb:d2:16:0c"
      - run:
          command: |
            ssh ubuntu@ec2-3-235-17-220.compute-1.amazonaws.com "bash deploy.sh"
  approval-job:

  # production-deploy:
  #   machine:
  #     enabled: true
  #   steps:
  #     - add_ssh_keys:
  #         fingerprints:
  #           - "fd:e0:e2:81:80:1b:4d:ee:be:7b:cd:a3:cb:d2:16:0c"
  #     - run:
  #         command: |
  #           ssh ubuntu@ec2-34-235-142-109.compute-1.amazonaws.com "bash deploy.sh"
workflows:
    build-and-test:
      jobs:
        - test
        - development-deploy:
            requires:
              - test
            filters:
              branches:
                only: master
        - approval-job:
            type: approval
            requires:
              - development-deploy
            filters:
              branches:
                only: master
        # - production-deploy:
        #     requires:
        #       - approval-job
        #     filters:
        #       branches:
        #         only: master